import React from 'react'
import { View } from 'react-native'
import SkeletonPlaceholder from 'react-native-skeleton-placeholder'
import { tailwind } from '@/tailwind'

const FournisseursConfiguresPlaceholder = () => {
  return (
    <View style={tailwind('mt-4 mb-4')}>
      <SkeletonPlaceholder>
        <SkeletonPlaceholder.Item
          flexDirection="column"
          marginLeft={10}
          marginRight={10}
          marginBottom={15}
          alignItems="center"
        >
          <SkeletonPlaceholder.Item
            marginLeft={15}
            flexDirection="column"
            alignItems="center"
            width={'100%'}
          >
            <SkeletonPlaceholder.Item
              width={250}
              height={10}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              width={180}
              height={10}
              borderRadius={4}
              marginTop={5}
              marginBottom={10}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={15}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            width={300}
            height={55}
            marginTop={25}
            borderRadius={5}
          />
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          flexDirection="column"
          marginLeft={10}
          marginRight={10}
          marginBottom={15}
          alignItems="center"
        >
          <SkeletonPlaceholder.Item
            marginLeft={15}
            flexDirection="column"
            alignItems="center"
            width={'100%'}
          >
            <SkeletonPlaceholder.Item
              width={250}
              height={10}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              width={180}
              height={10}
              borderRadius={4}
              marginTop={5}
              marginBottom={10}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={15}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            width={300}
            height={55}
            marginTop={25}
            borderRadius={5}
          />
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          flexDirection="column"
          marginLeft={10}
          marginRight={10}
          marginBottom={15}
          alignItems="center"
        >
          <SkeletonPlaceholder.Item
            marginLeft={15}
            flexDirection="column"
            alignItems="center"
            width={'100%'}
          >
            <SkeletonPlaceholder.Item
              width={250}
              height={10}
              borderRadius={4}
            />
            <SkeletonPlaceholder.Item
              width={180}
              height={10}
              borderRadius={4}
              marginTop={5}
              marginBottom={10}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={15}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            paddingLeft={15}
            paddingRight={15}
            width={'100%'}
            marginTop={10}
            flexDirection="row"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item width={60} height={10} borderRadius={4} />
            <SkeletonPlaceholder.Item
              width={100}
              height={10}
              borderRadius={4}
            />
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            width={300}
            height={55}
            marginTop={25}
            borderRadius={5}
          />
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder>
    </View>
  )
}

FournisseursConfiguresPlaceholder.propTypes = {}

FournisseursConfiguresPlaceholder.defaultProps = {}

export default FournisseursConfiguresPlaceholder
