import React from 'react'
import { View } from 'react-native'
import SkeletonPlaceholder from 'react-native-skeleton-placeholder'
import { tailwind } from '@/tailwind'

const RoleItemPlaceholder = () => {
  return (
    <View style={tailwind('content-center')}>
      <SkeletonPlaceholder>
        <SkeletonPlaceholder.Item
          flexDirection="column"
          width="95%"
          alignItems="center"
        >
          <SkeletonPlaceholder.Item
            padding={15}
            paddingBottom={0}
            width="85%"
            flexDirection="row"
            alignItems="center"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            padding={15}
            paddingBottom={0}
            width="85%"
            flexDirection="row"
            alignItems="center"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
          </SkeletonPlaceholder.Item>
          <SkeletonPlaceholder.Item
            padding={15}
            paddingBottom={0}
            width="85%"
            flexDirection="row"
            alignItems="center"
            justifyContent="space-between"
          >
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              flexDirection="column"
              alignItems="center"
              width={'10%'}
            >
              <SkeletonPlaceholder.Item
                alignItems="center"
                width={50}
                height={50}
                borderRadius={100}
              />
              <SkeletonPlaceholder.Item
                marginTop={6}
                width={80}
                height={10}
                borderRadius={4}
              />
            </SkeletonPlaceholder.Item>
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder>
    </View>
  )
}

RoleItemPlaceholder.propTypes = {}

RoleItemPlaceholder.defaultProps = {}

export default RoleItemPlaceholder
